import { useEffect, useState } from 'react';
import { api } from './api.js';
import { Modal, Icon } from './ui.jsx';
import { useLeaveGuard } from './useLeaveGuard.js';
import Consequences from './Consequences.jsx';

const briefFields = [
  ['purpose','What is this for?','The everyday problem this project should solve.'],
  ['keepWorking','What must keep working?','One example per line, such as: Save a note, close the app, and find it again.'],
  ['decisions','Decisions worth remembering','One per line. Include why you chose this approach.'],
  ['setup','How to get it running','One step per line. Include the tools and versions it needs.'],
  ['credentialPointers','Where access is kept','Names or locations only, such as: Database login is in my password manager. Never paste passwords or keys.'],
  ['pendingDecisions','Still to figure out','Questions and unfinished decisions for the next person or agent.'],
];
const blankResource = () => ({id:crypto.randomUUID(),name:'',kind:'hosting',provider:'',purpose:'',sharedWith:[],monthlyLow:null,monthlyHigh:null,currency:'USD',costSource:'',costCheckedAt:'',status:'unknown',evidence:'',sharedImpactReviewed:false});
const lines = value => value.split('\n').map(s => s.trim()).filter(Boolean);

export default function ProjectCare({ id, onUpdated, onBlocked, onSimplify }) {
  const [state, setState] = useState(null), [document, setDocument] = useState(null);
  const [edited, setEdited] = useState(false), [busy, setBusy] = useState(false);
  const [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [resource, setResource] = useState(null), [check, setCheck] = useState(null);
  const [section, setSection] = useState('Your brief');
  useLeaveGuard(edited || busy || !!resource || !!check, onBlocked);
  useEffect(() => {let active = true; api(`/projects/${id}/care`).then(value => {if (active) {setState(value);setDocument(value.document);}}).catch(e => {if (active) setError(e.message);}); return () => {active = false;};}, [id]);
  async function run(action, success) {
    setBusy(true); setError(''); setNotice('');
    try {const value = await action(); if (value?.document) {setState(value);setDocument(value.document);setEdited(false);} setNotice(success); setResource(null); setCheck(null); try {await onUpdated();} catch {setNotice(`${success} Refresh the project to update its saved status.`);} }
    catch(e) {setError(e.message);} finally {setBusy(false);}
  }
  function updateBrief(key, value) {setEdited(true);setDocument(current => ({...current,brief:{...current.brief,[key]:key === 'purpose' ? value : value.split('\n')}}));}
  async function save(event) {event.preventDefault(); await run(() => api(`/projects/${id}/care`,{document,expectedRevision:state.revision}),'Project notes written. Save a version to include them in history.');}
  async function saveResource(event) {event.preventDefault(); const resources = [...document.resources.filter(item => item.id !== resource.id),resource]; await run(() => api(`/projects/${id}/care`,{document:{...document,resources},expectedRevision:state.revision}),'Service record written. Save a version to keep it in history.');}
  async function simplify() {setBusy(true);setError('');try {const result = await api(`/projects/${id}/simplify`);onSimplify(result.request);} catch(e) {setError(e.message);} finally {setBusy(false);}}
  if (!document) return <p role={error ? 'alert' : 'status'}>{error || 'Opening your project notes…'}</p>;
  return <section className="project-care">
    <div className="section-heading"><div><h2>A project that remembers why.</h2><p>Keep its purpose, promises, and running costs with the code. Any coding tool can read them.</p></div><a className={`button secondary ${edited || busy ? 'disabled' : ''}`} aria-disabled={edited || busy} href={edited || busy ? undefined : `/api/projects/${id}/handoff`}>Download handoff<Icon name="export"/></a></div>
    <nav className="subtabs" aria-label="Project care views">{['Your brief','Services & costs','Behavior checks','Consequences'].map(label => <button className={section === label ? 'selected' : 'secondary'} disabled={busy || edited} key={label} onClick={() => setSection(label)}>{label}</button>)}</nav>
    {error && <p role="alert" className="error">{error}</p>}{notice && <p role="status" className="notice">{notice}</p>}
    {section === 'Your brief' && <form onSubmit={save} className="brief-form">{briefFields.map(([key,label,hint]) => <label key={key}>{label}<span className="field-hint">{hint}</span><textarea rows={key === 'purpose' ? 3 : 4} maxLength={key === 'purpose' ? 2000 : 24000} disabled={busy} value={key === 'purpose' ? document.brief[key] : document.brief[key].join('\n')} onChange={e => updateBrief(key,e.target.value)}/></label>)}<div className="form-actions"><button type="button" className="secondary" disabled={!edited || busy} onClick={() => {setDocument(state.document);setEdited(false);setError('');}}>Discard these edits</button><button disabled={!edited || busy}>{busy ? 'Writing…' : 'Write project notes'}</button></div></form>}
    {section === 'Services & costs' && <><div className="section-heading"><div><h3>Everything the project depends on.</h3><p>Record hosting, databases, domains, AI, storage, backups, email, and recurring chores. Amounts below are your estimates, not live billing.</p></div><button disabled={busy} onClick={() => setResource(blankResource())}>Add a service<Icon name="plus"/></button></div><div className="care-rows">{document.resources.map(item => <article key={item.id}><div className="section-heading"><div><h3>{item.name}</h3><p>{item.provider || item.kind} · {item.status === 'unknown' ? 'Status needs checking' : item.status}</p></div><button className="secondary" onClick={() => setResource({...item})}>Edit {item.name}</button></div><p>{item.purpose}</p><p>{item.monthlyLow == null ? 'Monthly cost not recorded' : `${item.currency} ${item.monthlyLow}–${item.monthlyHigh ?? item.monthlyLow} / month · your estimate`}</p>{item.sharedWith.length > 0 && <p className="notice">Shared with: {item.sharedWith.join(', ')}. Stopping it may affect those projects.</p>}{item.evidence && <p className="note">Evidence: {item.evidence}</p>}</article>)}</div>{!document.resources.length && <div className="empty"><h3>No service records yet.</h3><p>Start with the accounts you already use. Leave unknown amounts blank.</p></div>}</>}
    {section === 'Behavior checks' && <><h3>Prove the things you actually use.</h3><p>Run each example in your app, then record what happened. These are human observations; Unforge does not execute the app or certify the result.</p><div className="care-rows">{document.brief.keepWorking.filter(Boolean).map((example,index) => {const latest = [...(document.checks || [])].reverse().find(item => item.example === example);return <article key={index}><h3>{example}</h3><p>{latest ? `${latest.outcome === 'pass' ? 'Observed working' : latest.outcome === 'fail' ? 'Needs repair' : 'Not checked'} · ${new Date(latest.checkedAt).toLocaleString()}` : 'No observation recorded yet.'}</p>{latest?.note && <p>{latest.note}</p>}<button className="secondary" onClick={() => setCheck({example,outcome:'pass',note:''})}>Record an observation</button></article>;})}</div>{!document.brief.keepWorking.filter(Boolean).length && <p>Add examples under “What must keep working?” in your brief first.</p>}</>}
    {section === 'Consequences' && <><Consequences report={state.impact}/><div className="ownership-banner"><div><h2>Less to maintain.</h2><p>Prepare a simplification request that preserves your required behaviors and asks for evidence before removing anything.</p></div><button className="secondary" disabled={busy} onClick={simplify}>Make this simpler<Icon name="arrow"/></button></div><p className="note">Opens a request for review. Starting Codex is a separate action that uses your configured account.</p></>}
    {resource && <Modal title={document.resources.some(item => item.id === resource.id) ? 'Update service record' : 'Add a service'} busy={busy} onClose={() => setResource(null)}><form onSubmit={saveResource}>
      <label>Service name<input autoFocus required maxLength={160} value={resource.name} onChange={e => setResource({...resource,name:e.target.value})}/></label>
      <div className="form-grid"><label>Kind<select value={resource.kind} onChange={e => setResource({...resource,kind:e.target.value})}>{['hosting','database','storage','ai','email','domain','automation','backup','other'].map(kind => <option key={kind}>{kind}</option>)}</select></label><label>Provider<input maxLength={160} value={resource.provider} onChange={e => setResource({...resource,provider:e.target.value})}/></label></div>
      <label>What does it do?<textarea rows={2} maxLength={1000} value={resource.purpose} onChange={e => setResource({...resource,purpose:e.target.value})}/></label>
      <div className="form-grid"><label>Monthly low<input type="number" min="0" step="0.01" value={resource.monthlyLow ?? ''} onChange={e => setResource({...resource,monthlyLow:e.target.value === '' ? null : Number(e.target.value)})}/></label><label>Monthly high<input type="number" min="0" step="0.01" value={resource.monthlyHigh ?? ''} onChange={e => setResource({...resource,monthlyHigh:e.target.value === '' ? null : Number(e.target.value)})}/></label></div>
      <div className="form-grid"><label>Currency<input required maxLength={3} pattern="[A-Z]{3}" value={resource.currency} onChange={e => setResource({...resource,currency:e.target.value.toUpperCase()})}/></label><label>Date cost checked<input type="date" value={resource.costCheckedAt} onChange={e => setResource({...resource,costCheckedAt:e.target.value})}/></label></div>
      <label>Where did the estimate come from?<input maxLength={1000} placeholder="Invoice, pricing page, or calculation" value={resource.costSource} onChange={e => setResource({...resource,costSource:e.target.value})}/></label>
      <label>Other projects that share it<textarea rows={2} value={resource.sharedWith.join('\n')} onChange={e => setResource({...resource,sharedWith:e.target.value.split('\n')})}/><span className="field-hint">One project name or ID per line.</span></label>
      <label>Status<select value={resource.status} onChange={e => setResource({...resource,status:e.target.value})}><option value="unknown">Needs checking</option><option value="active">Active</option><option value="stopped">Stopped and checked</option><option value="retained">Intentionally keeping</option></select></label>
      {!!lines(resource.sharedWith.join('\n')).length && <label className="check-label"><input type="checkbox" checked={resource.sharedImpactReviewed} onChange={e => setResource({...resource,sharedImpactReviewed:e.target.checked})}/>I checked the impact on the other projects.</label>}
      <label>Evidence & remaining charges<textarea rows={3} maxLength={2000} placeholder="What you checked, when, and any storage or other charges that remain." value={resource.evidence} onChange={e => setResource({...resource,evidence:e.target.value})}/></label>
      <p className="note">This record travels with the project. Include no passwords, API keys, or private billing documents.</p>{error && <p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setResource(null)}>Cancel</button><button disabled={busy}>{busy ? 'Writing…' : 'Write service record'}</button></div>
    </form></Modal>}
    {check && <Modal title="What happened when you tried it?" busy={busy} onClose={() => setCheck(null)}><form onSubmit={e => {e.preventDefault();run(() => api(`/projects/${id}/behavior-check`,{...check,expectedRevision:state.revision}),'Observation written. Save a version to keep it in history.');}}><p>{check.example}</p><label>Result<select value={check.outcome} onChange={e => setCheck({...check,outcome:e.target.value})}><option value="pass">It worked</option><option value="fail">It failed</option><option value="not-run">Could not check</option></select></label><label>What did you observe?<textarea autoFocus required maxLength={2000} rows={4} value={check.note} onChange={e => setCheck({...check,note:e.target.value})}/></label><p className="note">Include the device, steps, and visible result. Avoid customer data and credentials.</p>{error && <p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={() => setCheck(null)} disabled={busy}>Cancel</button><button disabled={busy}>Record observation</button></div></form></Modal>}
  </section>;
}
