import { useEffect, useState } from 'react';
import { api } from './api.js';
import { Icon, Modal } from './ui.jsx';
import { useLeaveGuard } from './useLeaveGuard.js';

export default function Recovery({ id, dirty, onUpdated, onBlocked, onOpenProject }) {
  const [state, setState] = useState(null), [care, setCare] = useState(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [assets, setAssets] = useState([]), [creating, setCreating] = useState(false), [restoring, setRestoring] = useState(null);
  const [retiring, setRetiring] = useState(false), [selected, setSelected] = useState(''), [note, setNote] = useState('');
  const [copy, setCopy] = useState(null), [reviewAgain, setReviewAgain] = useState(false);
  useLeaveGuard(busy || creating || !!restoring || retiring, onBlocked);
  async function load() {const [recovery, projectCare] = await Promise.all([api(`/projects/${id}/recovery`),api(`/projects/${id}/care`)]);setState(recovery);setCare(projectCare);}
  useEffect(() => {load().catch(e => setError(e.message));}, [id]);
  async function run(action, message) {setBusy(true);setError('');setNotice('');let completed = false;try {await action();completed = true;setCreating(false);setRestoring(null);setRetiring(false);setReviewAgain(false);setNotice(message);await load();await onUpdated();} catch(e) {setError(completed ? `${message} The view could not refresh: ${e.message}` : e.message);} finally {setBusy(false);}}
  const rehearsed = capsule => state?.rehearsals.find(receipt => receipt.capsuleId === capsule.id && receipt.capsuleSha256 === capsule.sha256);
  const currentCapsules = state?.capsules.filter(capsule => rehearsed(capsule) && capsule.sourceHead === care?.retirement.sourceHead) || [];
  return <section className="recovery">
    <div className="section-heading"><div><h2>Know what you can get back.</h2><p>Capture saved source and the local data you declare. Reconstruct a separate copy and check that the pieces survived.</p></div><button disabled={busy || dirty} onClick={() => {setAssets([]);setCreating(true);setError('');}}>Create recovery capsule<Icon name="plus"/></button></div>
    {dirty && <p className="notice">Save a version before capturing recovery material or completing a retirement plan.</p>}
    {error && <p role="alert" className="error">{error}</p>}{notice && <p role="status" className="notice">{notice}</p>}
    {copy && <p className="notice">A separate project was restored. <button className="text-button" disabled={busy} onClick={() => onOpenProject(copy.id)}>Open {copy.name}<Icon name="arrow"/></button></p>}
    {!state ? <p role="status">Reading recovery records…</p> : <>
      {!state.capsules.length && <div className="empty"><h3>No recovery capsule yet.</h3><p>Start with saved source. Add local uploads or a SQLite database when your project has them.</p></div>}
      <div className="care-rows">{state.capsules.map(capsule => {const evidence = rehearsed(capsule);return <article key={capsule.id}><div className="section-heading"><div><h3>{capsule.sourceOnly ? 'Saved source' : 'Source & declared local data'}</h3><p>{new Date(capsule.createdAt).toLocaleString()} · {(capsule.bytes / 1024 / 1024).toFixed(2)} MiB · saved history{capsule.fileCount > 1 ? ` + ${capsule.fileCount - 1} data file${capsule.fileCount === 2 ? '' : 's'}` : ''}</p></div><span className={`status-label ${evidence ? 'checked' : ''}`}>{evidence ? 'Reconstruction checked' : 'Not rehearsed'}</span></div>
        {!!capsule.assets.length && <p>Includes: {capsule.assets.map(asset => `${asset.path} (${asset.kind})`).join(', ')}</p>}
        <div className="inline-actions"><button className="secondary" disabled={busy} onClick={() => run(() => api(`/projects/${id}/recovery/${capsule.id}/rehearse`,{}),'Recovery reconstructed and checked in a temporary workspace. No app code was executed.')}>Rehearse recovery</button><a className={`button secondary ${busy ? 'disabled' : ''}`} href={`/api/projects/${id}/recovery/${capsule.id}/download`}>Download capsule<Icon name="export"/></a><button className="text-button" disabled={busy} onClick={() => setRestoring(capsule)}>Restore as a new project<Icon name="arrow"/></button></div>
        {evidence && <details><summary>What passed on {new Date(evidence.verifiedAt).toLocaleString()}</summary><ul>{evidence.checks.map(item => <li key={item}>{item}</li>)}</ul><p>{evidence.verifiedFiles} files verified; {evidence.sqliteChecks} SQLite integrity checks.</p><p className="note">The app was not executed. This does not verify logins, hosted databases, integrations, or your end-to-end application flows.</p></details>}
        <details><summary>Contents, omissions & checksum</summary><p className="note">Unencrypted archive. Keep it somewhere you trust; captured local data and Git history may be private.</p><ul>{capsule.omissions.map(item => <li key={item}>{item}</li>)}</ul><code>{capsule.sha256}</code></details>
      </article>;})}</div>
      <div className="ownership-banner"><div><h2>Keep a copy away from this computer.</h2><p>A local capsule protects against some mistakes. Download one to an independent backup location so a lost or broken computer does not take everything with it.</p></div></div>
      <section className="retirement"><h2>When you’re done with a project.</h2><p>Work through its service inventory, shared dependencies, and recovery evidence. Record what you stopped and what you are intentionally keeping.</p>
        {care?.document.retirement.state === 'complete' && <p className="notice">Retirement plan recorded on {new Date(care.document.retirement.recordedAt).toLocaleDateString()}. This records your evidence; it does not establish provider shutdown or zero billing.</p>}
        {(care?.document.retirement.state !== 'complete' || reviewAgain) && <ol className="retirement-checks">{care?.retirement.checks.map(item => <li key={item.id}><span className={`status-label ${item.complete ? 'checked' : ''}`}>{item.complete ? 'Ready' : 'To do'}</span><div><h3>{item.title}</h3><p>{item.reason}</p></div></li>)}<li><span className={`status-label ${currentCapsules.length ? 'checked' : ''}`}>{currentCapsules.length ? 'Ready' : 'To do'}</span><div><h3>Rehearse recovery for the current saved version</h3><p>{currentCapsules.length ? 'A matching recovery capsule has passed reconstruction.' : 'Create a capsule after saving service records, then rehearse it.'}</p></div></li></ol>}
        <details><summary>What still needs your judgment</summary>{care?.retirement.risks.map((risk,index) => <p className="note" key={index}>{risk}</p>)}</details>
        {care?.document.retirement.state === 'complete' && !reviewAgain ? <><p className="note">This historical record covers source version <code>{care.document.retirement.sourceHead?.slice(0,12)}</code> and its rehearsed capsule. Saving the record does not invalidate that evidence. Later changes need a new review.</p><button className="secondary" disabled={busy} onClick={() => setReviewAgain(true)}>Review the current project again</button></> : <button className="secondary" disabled={busy || dirty || !care?.retirement.canComplete || !currentCapsules.length} onClick={() => {setSelected(currentCapsules[0].id);setNote('');setRetiring(true);}}>Record completed retirement plan</button>}
        <p className="note">Use Services & costs in Project care to update resources. No accounts, deployments, or files are deleted by this action.</p>
      </section>
    </>}
    {creating && <Modal title="What should recovery include?" busy={busy} onClose={() => setCreating(false)}><form onSubmit={event => {event.preventDefault();run(() => api(`/projects/${id}/recovery`,{assets}),'Recovery capsule created. Rehearse it and download an independent copy.');}}>
      <p>Saved source and Git history are included. Add local data using paths inside this project.</p>{assets.map((asset,index) => <div className="asset-row" key={index}><label>Local data path {index + 1}<input required value={asset.path} placeholder="data/records.sqlite or uploads" onChange={e => setAssets(assets.map((item,i) => i === index ? {...item,path:e.target.value} : item))}/></label><label>Data kind {index + 1}<select value={asset.kind} onChange={e => setAssets(assets.map((item,i) => i === index ? {...item,kind:e.target.value} : item))}><option value="sqlite">SQLite database</option><option value="directory">Folder</option><option value="file">File</option></select></label><button type="button" className="text-button" aria-label={`Remove data path ${index + 1}`} onClick={() => setAssets(assets.filter((_,i) => i !== index))}><Icon name="close"/></button></div>)}
      <button type="button" className="text-button" disabled={busy || assets.length >= 100} onClick={() => setAssets([...assets,{path:'',kind:'sqlite'}])}>Add local data<Icon name="plus"/></button>
      <p className="note">Data paths must be ignored by your saved .gitignore so they stay separate from source. Up to 256 MiB and 10,000 archive entries. SQLite uses its backup API; pause writes to other files before capturing them.</p>
      <p className="note">Capsules are unencrypted. They exclude undeclared data, hosted databases, credentials kept elsewhere, and external Git LFS objects. Declared files and Git history may still contain private information.</p>{error && <p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setCreating(false)}>Cancel</button><button disabled={busy}>{busy ? 'Capturing…' : 'Create capsule'}</button></div>
    </form></Modal>}
    {restoring && <Modal title="Restore a separate local copy?" busy={busy} onClose={() => setRestoring(null)}><p>This reconstructs the captured source and declared data as a new project. You can inspect it before running anything.</p>{error && <p role="alert" className="error">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={() => setRestoring(null)}>Cancel</button><button disabled={busy} onClick={() => run(async () => setCopy(await api(`/projects/${id}/recovery/${restoring.id}/restore`,{})),'Recovery restored as a separate local project.')}>{busy ? 'Restoring…' : 'Restore new copy'}</button></div></Modal>}
    {retiring && <Modal title="Record your retirement evidence" busy={busy} onClose={() => setRetiring(false)}><form onSubmit={event => {event.preventDefault();run(() => api(`/projects/${id}/retirement`,{expectedRevision:care.revision,capsuleId:selected,note}),'Retirement plan written. Save a version to keep the record in history.');}}><label>Verified recovery capsule<select value={selected} onChange={e => setSelected(e.target.value)}>{currentCapsules.map(item => <option key={item.id} value={item.id}>{new Date(item.createdAt).toLocaleString()} · {item.sourceOnly ? 'source only' : 'source and local data'}</option>)}</select></label><label>What remains, and where is your independent backup?<textarea autoFocus required rows={4} maxLength={2000} value={note} onChange={e => setNote(e.target.value)}/></label><p className="note">This records your plan and observations. Check provider accounts and later invoices for residual storage, retained resources, and charges.</p>{error && <p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setRetiring(false)}>Cancel</button><button disabled={busy}>Record retirement plan</button></div></form></Modal>}
  </section>;
}
